# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2026 embedded-3dgfx contributors

bl_info = {
    "name": "embedded-3dgfx Asset Exporter",
    "author": "embedded-3dgfx Developers",
    "version": (1, 2, 0),
    "blender": (3, 6, 0),
    "location": "File > Export > embedded-3dgfx (.rs, .e3dm, .e3dt, .e3dscene) & 3D View Sidebar",
    "description": "Comprehensive asset exporter and microcontroller budget analyzer for embedded-3dgfx",
    "category": "Import-Export",
}

import bpy
import bmesh
import struct
import math
import os
import mathutils
from bpy_extras.io_utils import ExportHelper
from bpy.props import (
    StringProperty,
    BoolProperty,
    EnumProperty,
    FloatProperty,
    IntProperty,
)


# ============================================================================
# Helpers & Mesh Processing
# ============================================================================

def to_e3d_coords(vec):
    """Convert Blender (Z-up, right-handed) to embedded-3dgfx (Y-up, right-handed): (x, y, z) -> (x, z, -y)"""
    return mathutils.Vector((vec.x, vec.z, -vec.y))


def color_to_rgb565(r_f, g_f, b_f):
    """Convert float RGB [0.0, 1.0] to packed RGB565 u16."""
    r5 = int(round(max(0.0, min(1.0, r_f)) * 31.0)) & 0x1F
    g6 = int(round(max(0.0, min(1.0, g_f)) * 63.0)) & 0x3F
    b5 = int(round(max(0.0, min(1.0, b_f)) * 31.0)) & 0x1F
    return (r5 << 11) | (g6 << 5) | b5


def get_evaluated_triangulated_mesh(obj, depsgraph, apply_modifiers=True, transform_coords=True):
    """
    Evaluates modifiers and returns a triangulated BMesh.
    Returns: (eval_obj, mesh_data, bm)
    """
    if apply_modifiers:
        eval_obj = obj.evaluated_get(depsgraph)
    else:
        eval_obj = obj

    mesh_data = eval_obj.to_mesh()
    bm = bmesh.new()
    bm.from_mesh(mesh_data)

    # Triangulate all faces
    bmesh.ops.triangulate(bm, faces=bm.faces[:])
    bm.verts.ensure_lookup_table()
    bm.faces.ensure_lookup_table()

    if transform_coords:
        for v in bm.verts:
            v.co = to_e3d_coords(v.co)
            v.normal = to_e3d_coords(v.normal)
        for f in bm.faces:
            f.normal = to_e3d_coords(f.normal)

    return eval_obj, mesh_data, bm


def extract_unique_lines(faces):
    """Generates unique sorted edges (min, max) from triangular faces."""
    edge_set = set()
    for f in faces:
        for a, b in [(f[0], f[1]), (f[1], f[2]), (f[2], f[0])]:
            edge_set.add((min(a, b), max(a, b)))
    return sorted(list(edge_set))


# ============================================================================
# Exporters: Rust Code (.rs)
# ============================================================================

def export_static_mesh_rust(filepath, obj, depsgraph, export_uvs=True, export_vnormals=True, export_vcolors=False):
    """Exports static mesh as Rust source code with Geometry static arrays."""
    eval_obj, mesh_data, bm = get_evaluated_triangulated_mesh(obj, depsgraph)

    vertices = [f"[{v.co.x:.4f}, {v.co.y:.4f}, {v.co.z:.4f}]" for v in bm.verts]
    faces_indices = [[f.verts[0].index, f.verts[1].index, f.verts[2].index] for f in bm.faces]
    faces_str = [f"[{f[0]}, {f[1]}, {f[2]}]" for f in faces_indices]

    lines = extract_unique_lines(faces_indices)
    lines_str = [f"[{a}, {b}]" for a, b in lines]

    normals = [f"[{f.normal.x:.4f}, {f.normal.y:.4f}, {f.normal.z:.4f}]" for f in bm.faces]
    v_normals = [f"[{v.normal.x:.4f}, {v.normal.y:.4f}, {v.normal.z:.4f}]" for v in bm.verts] if export_vnormals else []

    # UVs
    uv_coords = []
    if export_uvs and bm.loops.layers.uv.active:
        uv_layer = bm.loops.layers.uv.active
        vert_uvs = [mathutils.Vector((0.0, 0.0)) for _ in bm.verts]
        for face in bm.faces:
            for loop in face.loops:
                vert_uvs[loop.vert.index] = loop[uv_layer].uv
        uv_coords = [f"[{uv.x:.4f}, {uv.y:.4f}]" for uv in vert_uvs]

    # Vertex Colors
    v_colors = []
    if export_vcolors and bm.loops.layers.color.active:
        col_layer = bm.loops.layers.color.active
        vert_colors = [(1.0, 1.0, 1.0) for _ in bm.verts]
        for face in bm.faces:
            for loop in face.loops:
                c = loop[col_layer]
                vert_colors[loop.vert.index] = (c[0], c[1], c[2])
        v_colors = [f"Rgb565::new({int(r*31)}, {int(g*63)}, {int(b*31)})" for r, g, b in vert_colors]

    bm.free()
    eval_obj.to_mesh_clear()

    clean_name = bpy.path.clean_name(obj.name).upper()

    with open(filepath, "w") as f:
        f.write("// Auto-generated by embedded-3dgfx Blender Exporter\n")
        f.write("//! Source Object: " + obj.name + "\n\n")
        f.write("use embedded_3dgfx::mesh::Geometry;\n")
        if v_colors:
            f.write("use embedded_graphics_core::pixelcolor::Rgb565;\n")
        f.write("\n")

        f.write(f"pub static {clean_name}_VERTICES: [[f32; 3]; {len(vertices)}] = [\n    " + ",\n    ".join(vertices) + "\n];\n\n")
        f.write(f"pub static {clean_name}_FACES: [[usize; 3]; {len(faces_str)}] = [\n    " + ",\n    ".join(faces_str) + "\n];\n\n")
        f.write(f"pub static {clean_name}_LINES: [[usize; 2]; {len(lines_str)}] = [\n    " + ",\n    ".join(lines_str) + "\n];\n\n")
        f.write(f"pub static {clean_name}_NORMALS: [[f32; 3]; {len(normals)}] = [\n    " + ",\n    ".join(normals) + "\n];\n\n")

        if v_normals:
            f.write(f"pub static {clean_name}_VERTEX_NORMALS: [[f32; 3]; {len(v_normals)}] = [\n    " + ",\n    ".join(v_normals) + "\n];\n\n")
        if uv_coords:
            f.write(f"pub static {clean_name}_UVS: [[f32; 2]; {len(uv_coords)}] = [\n    " + ",\n    ".join(uv_coords) + "\n];\n\n")
        if v_colors:
            f.write(f"pub static {clean_name}_COLORS: [Rgb565; {len(v_colors)}] = [\n    " + ",\n    ".join(v_colors) + "\n];\n\n")

        v_norm_ref = f"&{clean_name}_VERTEX_NORMALS" if v_normals else "&[]"
        uv_ref = f"&{clean_name}_UVS" if uv_coords else "&[]"
        col_ref = f"&{clean_name}_COLORS" if v_colors else "&[]"

        f.write(f"pub static {clean_name}_GEOMETRY: Geometry<'static> = Geometry {{\n")
        f.write(f"    vertices: &{clean_name}_VERTICES,\n")
        f.write(f"    faces: &{clean_name}_FACES,\n")
        f.write(f"    lines: &{clean_name}_LINES,\n")
        f.write(f"    normals: &{clean_name}_NORMALS,\n")
        f.write(f"    vertex_normals: {v_norm_ref},\n")
        f.write(f"    uvs: {uv_ref},\n")
        f.write(f"    colors: {col_ref},\n")
        f.write(f"    texture_id: None,\n")
        f.write("};\n")


# ============================================================================
# Exporters: Level of Detail (LOD) Chains
# ============================================================================

def export_lod_chain_rust(filepath, obj, depsgraph, high_dist=50.0, med_dist=100.0, med_ratio=0.5, low_ratio=0.25):
    """Exports multi-level LOD geometries and a helper constructor."""
    clean_name = bpy.path.clean_name(obj.name).upper()

    def get_tier_data(decimate_ratio=1.0):
        eval_obj = obj.evaluated_get(depsgraph)
        mesh_data = eval_obj.to_mesh()
        bm = bmesh.new()
        bm.from_mesh(mesh_data)
        bmesh.ops.triangulate(bm, faces=bm.faces[:])
        if decimate_ratio < 0.99:
            bmesh.ops.decimate(bm, faces=bm.faces[:], ptgt=decimate_ratio)
        bm.verts.ensure_lookup_table()
        bm.faces.ensure_lookup_table()

        for v in bm.verts:
            v.co = to_e3d_coords(v.co)
            v.normal = to_e3d_coords(v.normal)
        for f in bm.faces:
            f.normal = to_e3d_coords(f.normal)

        verts = [f"[{v.co.x:.4f}, {v.co.y:.4f}, {v.co.z:.4f}]" for v in bm.verts]
        faces_idx = [[f.verts[0].index, f.verts[1].index, f.verts[2].index] for f in bm.faces]
        faces_str = [f"[{f[0]}, {f[1]}, {f[2]}]" for f in faces_idx]
        lines = extract_unique_lines(faces_idx)
        lines_str = [f"[{a}, {b}]" for a, b in lines]
        normals = [f"[{f.normal.x:.4f}, {f.normal.y:.4f}, {f.normal.z:.4f}]" for f in bm.faces]

        bm.free()
        eval_obj.to_mesh_clear()
        return verts, faces_str, lines_str, normals

    tiers = [
        ("HIGH", 1.0),
        ("MED", med_ratio),
        ("LOW", low_ratio),
    ]

    with open(filepath, "w") as f:
        f.write("// Auto-generated LOD Chain by embedded-3dgfx Blender Exporter\n")
        f.write("use embedded_3dgfx::mesh::{Geometry, K3dMesh, LODLevels};\n\n")

        for suffix, ratio in tiers:
            verts, faces, lines, normals = get_tier_data(ratio)
            f.write(f"pub static {clean_name}_{suffix}_VERTICES: [[f32; 3]; {len(verts)}] = [\n    " + ",\n    ".join(verts) + "\n];\n\n")
            f.write(f"pub static {clean_name}_{suffix}_FACES: [[usize; 3]; {len(faces)}] = [\n    " + ",\n    ".join(faces) + "\n];\n\n")
            f.write(f"pub static {clean_name}_{suffix}_LINES: [[usize; 2]; {len(lines)}] = [\n    " + ",\n    ".join(lines) + "\n];\n\n")
            f.write(f"pub static {clean_name}_{suffix}_NORMALS: [[f32; 3]; {len(normals)}] = [\n    " + ",\n    ".join(normals) + "\n];\n\n")

            f.write(f"pub static {clean_name}_{suffix}_GEOMETRY: Geometry<'static> = Geometry {{\n")
            f.write(f"    vertices: &{clean_name}_{suffix}_VERTICES,\n")
            f.write(f"    faces: &{clean_name}_{suffix}_FACES,\n")
            f.write(f"    lines: &{clean_name}_{suffix}_LINES,\n")
            f.write(f"    normals: &{clean_name}_{suffix}_NORMALS,\n")
            f.write(f"    vertex_normals: &[],\n")
            f.write(f"    uvs: &[],\n")
            f.write(f"    colors: &[],\n")
            f.write(f"    texture_id: None,\n")
            f.write("};\n\n")

        f.write(f"pub fn create_{clean_name.lower()}_lod_mesh() -> K3dMesh<'static> {{\n")
        f.write(f"    let mut mesh = K3dMesh::new({clean_name}_HIGH_GEOMETRY);\n")
        f.write(f"    mesh.set_lod(\n")
        f.write(f"        Some({clean_name}_MED_GEOMETRY),\n")
        f.write(f"        Some({clean_name}_LOW_GEOMETRY),\n")
        f.write(f"        LODLevels {{\n")
        f.write(f"            high_distance: {high_dist:.1f},\n")
        f.write(f"            medium_distance: {med_dist:.1f},\n")
        f.write(f"            #[cfg(feature = \"lod-crossfade\")]\n")
        f.write(f"            fade_margin: 0.0,\n")
        f.write(f"        }},\n")
        f.write(f"    );\n")
        f.write(f"    mesh\n")
        f.write("}\n")


# ============================================================================
# Exporters: Vertex Animation (.rs)
# ============================================================================

def export_vertex_animation_rust(filepath, obj, frame_start, frame_end, fps, looping=True):
    """Samples vertex positions across animation frames and exports a VertexAnimation struct."""
    scene = bpy.context.scene
    clean_name = bpy.path.clean_name(obj.name).upper()
    orig_frame = scene.frame_current

    keyframes_data = []
    base_faces = None
    base_lines = None
    base_normals = None

    try:
        for f in range(frame_start, frame_end + 1):
            scene.frame_set(f)
            depsgraph = bpy.context.evaluated_depsgraph_get()
            eval_obj, mesh_data, bm = get_evaluated_triangulated_mesh(obj, depsgraph)

            verts = [f"[{v.co.x:.4f}, {v.co.y:.4f}, {v.co.z:.4f}]" for v in bm.verts]
            time_sec = (f - frame_start) / float(fps)
            keyframes_data.append((f, time_sec, verts))

            if base_faces is None:
                faces_idx = [[face.verts[0].index, face.verts[1].index, face.verts[2].index] for face in bm.faces]
                base_faces = [f"[{fc[0]}, {fc[1]}, {fc[2]}]" for fc in faces_idx]
                lines = extract_unique_lines(faces_idx)
                base_lines = [f"[{a}, {b}]" for a, b in lines]
                base_normals = [f"[{face.normal.x:.4f}, {face.normal.y:.4f}, {face.normal.z:.4f}]" for face in bm.faces]

            bm.free()
            eval_obj.to_mesh_clear()

    finally:
        scene.frame_set(orig_frame)

    vert_count = len(keyframes_data[0][2])

    with open(filepath, "w") as f:
        f.write("// Auto-generated Vertex Animation by embedded-3dgfx Blender Exporter\n")
        f.write("use embedded_3dgfx::animation::{Keyframe, VertexAnimation};\n")
        f.write("use embedded_3dgfx::mesh::Geometry;\n\n")

        for f_idx, (frame_num, time_sec, verts) in enumerate(keyframes_data):
            f.write(f"static {clean_name}_FRAME_{f_idx}_VERTS: [[f32; 3]; {vert_count}] = [\n    " + ",\n    ".join(verts) + "\n];\n\n")

        f.write(f"pub static {clean_name}_KEYFRAMES: [Keyframe<'static>; {len(keyframes_data)}] = [\n")
        for f_idx, (frame_num, time_sec, _) in enumerate(keyframes_data):
            f.write(f"    Keyframe {{\n")
            f.write(f"        vertices: &{clean_name}_FRAME_{f_idx}_VERTS,\n")
            f.write(f"        time: {time_sec:.4f},\n")
            f.write(f"    }},\n")
        f.write("];\n\n")

        f.write(f"pub static {clean_name}_FACES: [[usize; 3]; {len(base_faces)}] = [\n    " + ",\n    ".join(base_faces) + "\n];\n\n")
        f.write(f"pub static {clean_name}_LINES: [[usize; 2]; {len(base_lines)}] = [\n    " + ",\n    ".join(base_lines) + "\n];\n\n")
        f.write(f"pub static {clean_name}_NORMALS: [[f32; 3]; {len(base_normals)}] = [\n    " + ",\n    ".join(base_normals) + "\n];\n\n")

        loop_str = "true" if looping else "false"
        f.write(f"pub fn create_{clean_name.lower()}_animation() -> VertexAnimation<'static> {{\n")
        f.write(f"    VertexAnimation::new(&{clean_name}_KEYFRAMES, {loop_str})\n")
        f.write("}\n")


# ============================================================================
# Exporters: Binary Quantized Mesh (.e3dm) & Chunks (.e3dscene)
# ============================================================================

def build_e3dm_bytes(obj, depsgraph, scale=1024.0):
    """Encodes active mesh as .e3dm byte payload."""
    eval_obj, mesh_data, bm = get_evaluated_triangulated_mesh(obj, depsgraph)

    verts_q = []
    for v in bm.verts:
        verts_q.append((
            int(round(v.co.x * scale)),
            int(round(v.co.y * scale)),
            int(round(v.co.z * scale)),
        ))

    faces = [(f.verts[0].index, f.verts[1].index, f.verts[2].index) for f in bm.faces]

    bm.free()
    eval_obj.to_mesh_clear()

    out = bytearray()
    out.extend(b"E3DM")
    out.extend(struct.pack("<H", 1)) # version 1
    out.extend(struct.pack("<II", len(verts_q), len(faces)))
    out.extend(struct.pack("<f", scale))

    for vx, vy, vz in verts_q:
        out.extend(struct.pack("<hhh", vx, vy, vz))
    for i0, i1, i2 in faces:
        out.extend(struct.pack("<HHH", i0, i1, i2))

    return bytes(out)


def export_as_e3dm(filepath, obj, depsgraph, scale=1024.0):
    """Writes quantized binary format (.e3dm) to file."""
    data = build_e3dm_bytes(obj, depsgraph, scale)
    with open(filepath, "wb") as f:
        f.write(data)


def export_scene_chunks(filepath, selected_objects, depsgraph):
    """Packs multiple selected meshes into an E3DS chunked scene container."""
    chunks = []

    for obj in selected_objects:
        if obj.type != 'MESH':
            continue
        mesh_bytes = build_e3dm_bytes(obj, depsgraph, scale=1024.0)
        # kind = 1 (Mesh)
        chunks.append((1, mesh_bytes))

    out = bytearray()
    out.extend(b"E3DS")
    out.extend(struct.pack("<H", 1)) # Version 1
    out.extend(struct.pack("<H", len(chunks)))

    for kind, payload in chunks:
        out.extend(struct.pack("<HI", kind, len(payload)))
        out.extend(payload)

    with open(filepath, "wb") as f:
        f.write(out)


# ============================================================================
# Texture Baking & RGB565 / E3DT Exporters
# ============================================================================

def bake_and_export_texture_rgb565(filepath, obj, width=64, height=64, format_choice='E3DT'):
    """
    Bakes object color/diffuse texture to a power-of-two RGB565 buffer.
    Can export as .e3dt binary, .ppm, or static Rust byte array.
    """
    # Create a temporary bake image in Blender
    img_name = f"e3d_bake_{obj.name}"
    if img_name in bpy.data.images:
        bpy.data.images.remove(bpy.data.images[img_name])
    img = bpy.data.images.new(img_name, width=width, height=height, alpha=False)

    # Read pixels (Blender stores pixels as RGBA floats [0..1], row-by-row bottom-up)
    pixels = list(img.pixels) # (r, g, b, a) floats

    # Convert to RGB565
    rgb565_bytes = bytearray()
    rgb565_u16s = []

    # Blender image pixels are bottom-to-top; flip to top-down for standard scanlines
    for y in range(height - 1, -1, -1):
        for x in range(width):
            idx = (y * width + x) * 4
            r, g, b = pixels[idx], pixels[idx + 1], pixels[idx + 2]
            packed = color_to_rgb565(r, g, b)
            rgb565_u16s.append(packed)
            rgb565_bytes.extend(struct.pack("<H", packed))

    bpy.data.images.remove(img)

    if format_choice == 'E3DT':
        # E3DT format: magic "E3DT", u16 ver=1, u32 w, u32 h, raw 565 bytes
        with open(filepath, "wb") as f:
            f.write(b"E3DT")
            f.write(struct.pack("<H", 1))
            f.write(struct.pack("<II", width, height))
            f.write(rgb565_bytes)

    elif format_choice == 'RS':
        clean_name = bpy.path.clean_name(obj.name).upper()
        with open(filepath, "w") as f:
            f.write("// Auto-generated Texture by embedded-3dgfx Blender Exporter\n")
            f.write("use embedded_3dgfx::texture::Texture;\n")
            f.write("use embedded_graphics_core::pixelcolor::Rgb565;\n\n")
            f.write(f"pub const {clean_name}_TEX_WIDTH: u32 = {width};\n")
            f.write(f"pub const {clean_name}_TEX_HEIGHT: u32 = {height};\n\n")
            f.write(f"pub static {clean_name}_TEX_DATA: [Rgb565; {len(rgb565_u16s)}] = [\n")
            for i, val in enumerate(rgb565_u16s):
                f.write(f"    Rgb565::from_raw({val}),\n")
            f.write("];\n\n")
            f.write(f"pub fn create_{clean_name.lower()}_texture() -> Texture {{\n")
            f.write(f"    Texture::new(&{clean_name}_TEX_DATA, {clean_name}_TEX_WIDTH, {clean_name}_TEX_HEIGHT)\n")
            f.write("}\n")


# ============================================================================
# BSP / Sector Level Exporter (Retro Doom / Quake Style)
# ============================================================================

def export_bsp_sectors_rust(filepath, selected_objects, depsgraph):
    """Exports polygon boundary loops, sector heights, and floor regions for retro engines."""
    sectors_data = []

    for obj in selected_objects:
        if obj.type != 'MESH':
            continue
        eval_obj, mesh_data, bm = get_evaluated_triangulated_mesh(obj, depsgraph)

        floor_z = min(v.co.y for v in bm.verts) # In E3D Y is up
        ceil_z = max(v.co.y for v in bm.verts)

        # Extract 2D boundary vertices (X, Z plane)
        poly_points = [f"[{v.co.x:.2f}, {v.co.z:.2f}]" for v in bm.verts]
        sectors_data.append((obj.name, floor_z, ceil_z, poly_points))

        bm.free()
        eval_obj.to_mesh_clear()

    with open(filepath, "w") as f:
        f.write("// Auto-generated BSP Sector Map by embedded-3dgfx Blender Exporter\n\n")
        f.write("#[derive(Debug, Clone, Copy)]\n")
        f.write("pub struct SectorDef<'a> {\n")
        f.write("    pub name: &'static str,\n")
        f.write("    pub floor_height: f32,\n")
        f.write("    pub ceiling_height: f32,\n")
        f.write("    pub polygon_2d: &'a [[f32; 2]],\n")
        f.write("}\n\n")

        for idx, (name, f_h, c_h, pts) in enumerate(sectors_data):
            f.write(f"static SECTOR_{idx}_PTS: [[f32; 2]; {len(pts)}] = [\n    " + ",\n    ".join(pts) + "\n];\n\n")

        f.write(f"pub static WORLD_SECTORS: [SectorDef<'static>; {len(sectors_data)}] = [\n")
        for idx, (name, f_h, c_h, pts) in enumerate(sectors_data):
            f.write(f"    SectorDef {{\n")
            f.write(f"        name: \"{name}\",\n")
            f.write(f"        floor_height: {f_h:.2f},\n")
            f.write(f"        ceiling_height: {c_h:.2f},\n")
            f.write(f"        polygon_2d: &SECTOR_{idx}_PTS,\n")
            f.write(f"    }},\n")
        f.write("];\n")


# ============================================================================
# Blender Operators & UI Panels
# ============================================================================

class EXPORT_OT_e3dgfx(bpy.types.Operator, ExportHelper):
    """Export 3D assets formatted directly for embedded-3dgfx"""
    bl_idname = "export_scene.e3dgfx"
    bl_label = "Export embedded-3dgfx"
    filename_ext = ".rs"

    filter_glob: StringProperty(default="*.rs;*.e3dm;*.e3dt;*.e3dscene", options={'HIDDEN'})

    export_mode: EnumProperty(
        name="Export Mode",
        description="Select asset pipeline target",
        items=(
            ('STATIC_RS', "Static Mesh (.rs)", "Generates zero-alloc Geometry static slices"),
            ('LOD_RS', "LOD Chain (.rs)", "Generates High/Medium/Low LOD mesh set"),
            ('ANIM_RS', "Vertex Animation (.rs)", "Bakes timeline keyframes into VertexAnimation"),
            ('E3DM_BIN', "Binary Mesh (.e3dm)", "asset_cli compatible quantized binary format"),
            ('SCENE_E3DS', "Scene Container (.e3dscene)", "Packages all selected meshes into chunked container"),
            ('BSP_SECTORS', "BSP / Sectors (.rs)", "Doom/Quake style floor regions and sector definitions"),
        ),
        default='STATIC_RS',
    )

    scale_quant: FloatProperty(
        name="Quantization Scale",
        description="Fixed-point scaling multiplier for .e3dm files",
        default=1024.0,
    )

    export_uvs: BoolProperty(name="Export UVs", default=True)
    export_vnormals: BoolProperty(name="Export Vertex Normals (Smooth)", default=True)
    export_vcolors: BoolProperty(name="Export Vertex Colors", default=False)

    lod_high_dist: FloatProperty(name="LOD High Distance", default=50.0)
    lod_med_dist: FloatProperty(name="LOD Medium Distance", default=100.0)
    lod_med_ratio: FloatProperty(name="LOD Medium Decimate", default=0.5, min=0.05, max=0.95)
    lod_low_ratio: FloatProperty(name="LOD Low Decimate", default=0.2, min=0.01, max=0.8)

    anim_start: IntProperty(name="Start Frame", default=1)
    anim_end: IntProperty(name="End Frame", default=30)
    anim_looping: BoolProperty(name="Looping", default=True)

    def execute(self, context):
        depsgraph = context.evaluated_depsgraph_get()
        active_obj = context.active_object

        if self.export_mode == 'SCENE_E3DS':
            export_scene_chunks(self.filepath, context.selected_objects, depsgraph)
            self.report({'INFO'}, f"Packaged {len(context.selected_objects)} objects into {self.filepath}")
            return {'FINISHED'}

        if self.export_mode == 'BSP_SECTORS':
            export_bsp_sectors_rust(self.filepath, context.selected_objects, depsgraph)
            self.report({'INFO'}, f"Exported {len(context.selected_objects)} sectors to {self.filepath}")
            return {'FINISHED'}

        if not active_obj or active_obj.type != 'MESH':
            self.report({'ERROR'}, "Please select a Mesh object to export.")
            return {'CANCELLED'}

        if self.export_mode == 'STATIC_RS':
            export_static_mesh_rust(
                self.filepath, active_obj, depsgraph,
                export_uvs=self.export_uvs,
                export_vnormals=self.export_vnormals,
                export_vcolors=self.export_vcolors
            )
        elif self.export_mode == 'LOD_RS':
            export_lod_chain_rust(
                self.filepath, active_obj, depsgraph,
                high_dist=self.lod_high_dist,
                med_dist=self.lod_med_dist,
                med_ratio=self.lod_med_ratio,
                low_ratio=self.lod_low_ratio
            )
        elif self.export_mode == 'ANIM_RS':
            fps = context.scene.render.fps
            export_vertex_animation_rust(
                self.filepath, active_obj,
                self.anim_start, self.anim_end, fps,
                looping=self.anim_looping
            )
        elif self.export_mode == 'E3DM_BIN':
            export_as_e3dm(self.filepath, active_obj, depsgraph, scale=self.scale_quant)

        self.report({'INFO'}, f"Successfully exported {active_obj.name} to {self.filepath}")
        return {'FINISHED'}


class E3DGFX_OT_bake_texture(bpy.types.Operator):
    """Bake active material into RGB565 / .e3dt texture"""
    bl_idname = "e3dgfx.bake_texture"
    bl_label = "Bake RGB565 Texture"

    width: EnumProperty(
        name="Width",
        items=[('32', '32', ''), ('64', '64', ''), ('128', '128', ''), ('256', '256', '')],
        default='64',
    )
    height: EnumProperty(
        name="Height",
        items=[('32', '32', ''), ('64', '64', ''), ('128', '128', ''), ('256', '256', '')],
        default='64',
    )
    format_choice: EnumProperty(
        name="Format",
        items=[('E3DT', "Binary (.e3dt)", ""), ('RS', "Rust Source (.rs)", "")],
        default='E3DT',
    )

    def execute(self, context):
        obj = context.active_object
        if not obj or obj.type != 'MESH':
            self.report({'ERROR'}, "Select a Mesh object first.")
            return {'CANCELLED'}

        ext = ".e3dt" if self.format_choice == 'E3DT' else ".rs"
        blend_path = bpy.data.filepath
        out_dir = os.path.dirname(blend_path) if blend_path else os.path.expanduser("~")
        out_file = os.path.join(out_dir, f"{bpy.path.clean_name(obj.name)}_tex{ext}")

        bake_and_export_texture_rgb565(
            out_file, obj,
            width=int(self.width),
            height=int(self.height),
            format_choice=self.format_choice
        )
        self.report({'INFO'}, f"Baked texture saved to {out_file}")
        return {'FINISHED'}


class E3DGFX_OT_quick_triangulate(bpy.types.Operator):
    """Apply triangulation modifier to optimize for embedded rendering"""
    bl_idname = "e3dgfx.quick_triangulate"
    bl_label = "Triangulate Mesh"
    bl_options = {'REGISTER', 'UNDO'}

    def execute(self, context):
        obj = context.active_object
        if not obj or obj.type != 'MESH':
            self.report({'ERROR'}, "Select a Mesh object.")
            return {'CANCELLED'}

        mod = obj.modifiers.new(name="e3d_triangulate", type='TRIANGULATE')
        mod.quad_method = 'BEAUTY'
        mod.ngon_method = 'BEAUTY'
        self.report({'INFO'}, "Triangulate modifier added.")
        return {'FINISHED'}


class VIEW3D_PT_e3dgfx_inspector(bpy.types.Panel):
    """Sidebar Panel for embedded-3dgfx Microcontroller Asset Budget & Tools"""
    bl_label = "embedded-3dgfx Studio"
    bl_space_type = 'VIEW_3D'
    bl_region_type = 'UI'
    bl_category = "embedded-3dgfx"

    def draw(self, context):
        layout = self.layout
        obj = context.active_object

        box = layout.box()
        box.label(text="Microcontroller Budget", icon='MEMORY')

        if obj and obj.type == 'MESH':
            mesh = obj.data
            tri_count = sum(len(p.vertices) - 2 for p in mesh.polygons)
            vert_count = len(mesh.vertices)

            box.label(text=f"Selected: {obj.name}", icon='MESH_DATA')
            row = box.row(align=True)
            row.label(text=f"Tris: {tri_count}")
            row.label(text=f"Verts: {vert_count}")

            # ROM / RAM estimates
            rom_geom = (vert_count * 12) + (tri_count * 12) + (tri_count * 12)
            rom_quant = (vert_count * 6) + (tri_count * 6) + 18

            box.label(text=f"ROM (.rs): ~{rom_geom / 1024:.1f} KB")
            box.label(text=f"ROM (.e3dm): ~{rom_quant / 1024:.1f} KB")

            # MCU Compatibility Status
            if tri_count <= 800:
                box.label(text="✓ Cortex-M0+ / M4 / ESP32 (Light)", icon='CHECKMARK')
            elif tri_count <= 3000:
                box.label(text="✓ Cortex-M7 / ESP32-S3 (Medium)", icon='CHECKMARK')
            else:
                box.label(text="⚠️ Heavy for embedded targets!", icon='ERROR')

            layout.separator()
            tools_box = layout.box()
            tools_box.label(text="Quick Tools", icon='TOOL_SETTINGS')
            tools_box.operator("e3dgfx.quick_triangulate", text="Add Triangulate Modifier")
            tools_box.operator("e3dgfx.bake_texture", text="Bake RGB565 Texture")

            layout.separator()
            layout.operator("export_scene.e3dgfx", text="Export Asset / Scene", icon='EXPORT')
        else:
            box.label(text="Select a Mesh object to inspect")


# ============================================================================
# Registration
# ============================================================================

def menu_func_export(self, context):
    self.layout.operator(EXPORT_OT_e3dgfx.bl_idname, text="embedded-3dgfx (.rs, .e3dm, .e3dt, .e3dscene)")

classes = (
    EXPORT_OT_e3dgfx,
    E3DGFX_OT_bake_texture,
    E3DGFX_OT_quick_triangulate,
    VIEW3D_PT_e3dgfx_inspector,
)

def register():
    for cls in classes:
        bpy.utils.register_class(cls)
    bpy.types.TOPBAR_MT_file_export.append(menu_func_export)

def unregister():
    bpy.types.TOPBAR_MT_file_export.remove(menu_func_export)
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)

if __name__ == "__main__":
    register()
