name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install SDL2
      run: |
        sudo apt-get update
        sudo apt-get install -y libsdl2-dev
    - name: Check library
      run: cargo check --lib --verbose
    - name: Run library tests
      run: cargo test --lib --verbose
    - name: Check with std feature
      run: cargo check --lib --features std --verbose
    - name: Check with all features
      run: cargo check --lib --all-features --verbose
